**Selecting & Filtering Data**

Goal: Learn how to extract exactly the rows and columns you need from a Pandas DataFrame.

In [1]:
import pandas as pd

students = {
    "Name": ["Tenzin", "Rahul", "Priya", "Arun", "Meena",
             "John", "David", "Anu"],
    "Age": [20, 21, 20, 22, 21, 20, 22, 21],
    "Department": ["CSE", "ECE", "CSE", "IT", "CSE",
                   "ECE", "IT", "CSE"],
    "Marks": [85, 78, 92, 74, 88, 81, 69, 95]
}

df = pd.DataFrame(students)

print(df)

     Name  Age Department  Marks
0  Tenzin   20        CSE     85
1   Rahul   21        ECE     78
2   Priya   20        CSE     92
3    Arun   22         IT     74
4   Meena   21        CSE     88
5    John   20        ECE     81
6   David   22         IT     69
7     Anu   21        CSE     95

**Selecting One Column**

In [2]:
print(df["Name"])
print(df["Marks"])

0    Tenzin
1     Rahul
2     Priya
3      Arun
4     Meena
5      John
6     David
7       Anu
Name: Name, dtype: object
0    85
1    78
2    92
3    74
4    88
5    81
6    69
7    95
Name: Marks, dtype: int64

**Selecting Multiple Columns**

In [3]:
df[["Name", "Department", "Marks"]]

     Name Department  Marks
0  Tenzin        CSE     85
1   Rahul        ECE     78
2   Priya        CSE     92
3    Arun         IT     74
4   Meena        CSE     88
5    John        ECE     81
6   David         IT     69
7     Anu        CSE     95

**.loc[]**

.loc[] is used for label-based selection.

In [8]:
print(df.loc[2, "Name"])  #[row_label, column_label]

#Select an entire row
print(df.loc[2])  #print entire row 2

#Select multiple rows
print(df.loc[1:4])

#select specific row
print(df.loc[[1, 3, 5]])

#.loc[] — Selecting Rows and Columns
print(df.loc[1:4, ["Name", "Marks"]])

Priya
Name          Priya
Age              20
Department      CSE
Marks            92
Name: 2, dtype: object
    Name  Age Department  Marks
1  Rahul   21        ECE     78
2  Priya   20        CSE     92
3   Arun   22         IT     74
4  Meena   21        CSE     88
    Name  Age Department  Marks
1  Rahul   21        ECE     78
3   Arun   22         IT     74
5   John   20        ECE     81
    Name  Marks
1  Rahul     78
2  Priya     92
3   Arun     74
4  Meena     88

**.iloc[]**

.iloc[] means integer-location based indexing.

In [10]:
print(df.iloc[2, 0])

#Select a row
print(df.iloc[2])

#Select multiple rows
print(df.iloc[1:5])

#Select a specific column by position
print(df.iloc[:, 0])

Priya
Name          Priya
Age              20
Department      CSE
Marks            92
Name: 2, dtype: object
    Name  Age Department  Marks
1  Rahul   21        ECE     78
2  Priya   20        CSE     92
3   Arun   22         IT     74
4  Meena   21        CSE     88
0    Tenzin
1     Rahul
2     Priya
3      Arun
4     Meena
5      John
6     David
7       Anu
Name: Name, dtype: object

**Boolean Filtering**

Boolean filtering means selecting rows based on a condition.

In [13]:
print(df["Marks"] > 80)

#Now use it to filter the DataFrame:
df[df["Marks"] > 80]

#Other Comparison Operators
print(df[df["Marks"] < 80])
print(df[df["Marks"] >= 80])
print(df[df["Marks"] == 85])
print(df[df["Marks"] != 85])

0     True
1    False
2     True
3    False
4     True
5     True
6    False
7     True
Name: Marks, dtype: bool
    Name  Age Department  Marks
1  Rahul   21        ECE     78
3   Arun   22         IT     74
6  David   22         IT     69
     Name  Age Department  Marks
0  Tenzin   20        CSE     85
2   Priya   20        CSE     92
4   Meena   21        CSE     88
5    John   20        ECE     81
7     Anu   21        CSE     95
     Name  Age Department  Marks
0  Tenzin   20        CSE     85
    Name  Age Department  Marks
1  Rahul   21        ECE     78
2  Priya   20        CSE     92
3   Arun   22         IT     74
4  Meena   21        CSE     88
5   John   20        ECE     81
6  David   22         IT     69
7    Anu   21        CSE     95

**Filtering Text**

You can also filter strings.

In [15]:
print(df[df["Department"] == "CSE"])
print(df[df["Department"] != "CSE"])

     Name  Age Department  Marks
0  Tenzin   20        CSE     85
2   Priya   20        CSE     92
4   Meena   21        CSE     88
7     Anu   21        CSE     95
    Name  Age Department  Marks
1  Rahul   21        ECE     78
3   Arun   22         IT     74
5   John   20        ECE     81
6  David   22         IT     69

**Multiple Conditions with &**

In [16]:
df[(df["Department"] == "CSE") & (df["Marks"] > 85)]

    Name  Age Department  Marks
2  Priya   20        CSE     92
4  Meena   21        CSE     88
7    Anu   21        CSE     95

**& vs and**

In [18]:
#Python and
#Used for normal single Boolean expressions.
#age > 20 and marks > 80

#Pandas &
#Used for element-wise conditions on Series.
(df["Age"] > 20) & (df["Marks"] > 80)

0    False
1    False
2    False
3    False
4     True
5    False
6    False
7     True
dtype: bool

**Multiple Conditions with |**

| means OR.

In [19]:
df[
    (df["Department"] == "CSE") |
    (df["Department"] == "ECE")
]

     Name  Age Department  Marks
0  Tenzin   20        CSE     85
1   Rahul   21        ECE     78
2   Priya   20        CSE     92
4   Meena   21        CSE     88
5    John   20        ECE     81
7     Anu   21        CSE     95

**| vs or**

In [20]:
#In Pandas:
#(condition1) | (condition2)

#In python:
#condition1 or condition2

**~ — Negation**

~ means NOT.

In [21]:
df[~(df["Department"] == "CSE")]

    Name  Age Department  Marks
1  Rahul   21        ECE     78
3   Arun   22         IT     74
5   John   20        ECE     81
6  David   22         IT     69

**.isin()**

.isin() is useful when checking whether a value belongs to a list of values.

In [23]:
df[(df["Department"] == "CSE") | (df["Department"] == "IT")]


#.isin() with numbers
print(df[df["Age"].isin([20, 22])])

#Negating .isin()
df[~df["Department"].isin(["CSE", "IT"])]

     Name  Age Department  Marks
0  Tenzin   20        CSE     85
2   Priya   20        CSE     92
3    Arun   22         IT     74
5    John   20        ECE     81
6   David   22         IT     69

    Name  Age Department  Marks
1  Rahul   21        ECE     78
5   John   20        ECE     81

**.between()**

.between() checks whether values fall within a range.

In [24]:
print(df[df["Marks"].between(80, 90)])

     Name  Age Department  Marks
0  Tenzin   20        CSE     85
4   Meena   21        CSE     88
5    John   20        ECE     81

**Selecting Rows and Columns Simultaneously**

In [25]:
df.loc[
    (df["Department"] == "CSE") & (df["Marks"] > 85),
    ["Name", "Marks"]
]

    Name  Marks
2  Priya     92
4  Meena     88
7    Anu     95

In [26]:
#Combining Everything
result = df.loc[
    (df["Department"].isin(["CSE", "ECE"])) &
    (df["Age"].between(20, 21)) &
    (df["Marks"] > 80),
    ["Name", "Age", "Marks"]
]

print(result)

     Name  Age  Marks
0  Tenzin   20     85
2   Priya   20     92
4   Meena   21     88
5    John   20     81
7     Anu   21     95