**Data Cleaning**

Goal: Turn messy, inconsistent, or incomplete data into a clean dataset that can be used for analysis and machine learning.

In [42]:
#Create a Messy Dataset
import pandas as pd

data = {
    "Name": ["Tenzin", "Rahul", "Priya", "Arun", "Tenzin", None],
    "Age": [20, 21, "20", 22, 20, 21],
    "Department": ["CSE", "cse", "CSE", "IT", "CSE", "IT"],
    "Marks": [85, None, 92, "74", 85, 88],
    "City": ["Leh", "Delhi", "Leh", None, "Leh", "Delhi"]
}

df = pd.DataFrame(data)

print(df)

     Name Age Department Marks   City
0  Tenzin  20        CSE    85    Leh
1   Rahul  21        cse  None  Delhi
2   Priya  20        CSE    92    Leh
3    Arun  22         IT    74   None
4  Tenzin  20        CSE    85    Leh
5    None  21         IT    88  Delhi

**isna()**

isna() detects missing values.

In [4]:
print(df.isna())

#Count missing values
print(df.isna().sum())

    Name    Age  Department  Marks   City
0  False  False       False  False  False
1  False  False       False   True  False
2  False  False       False  False  False
3  False  False       False  False   True
4  False  False       False  False  False
5   True  False       False  False  False
Name          1
Age           0
Department    0
Marks         1
City          1
dtype: int64

**notna()**

notna() is the opposite of isna().

In [6]:
#This selects rows where Name is not missing.
print(df[df["Name"].notna()])

     Name Age Department Marks   City
0  Tenzin  20        CSE    85    Leh
1   Rahul  21        cse  None  Delhi
2   Priya  20        CSE    92    Leh
3    Arun  22         IT    74   None
4  Tenzin  20        CSE    85    Leh

**dropna()**

dropna() removes rows containing missing values.

In [9]:
print(df.dropna())

#dropna() does not normally modify the original DataFrame.
clean_df = df.dropna()
print(clean_df)

#Drop rows where a specific column is missing
df.dropna(subset=["Marks"])

     Name Age Department Marks City
0  Tenzin  20        CSE    85  Leh
2   Priya  20        CSE    92  Leh
4  Tenzin  20        CSE    85  Leh
     Name Age Department Marks City
0  Tenzin  20        CSE    85  Leh
2   Priya  20        CSE    92  Leh
4  Tenzin  20        CSE    85  Leh

     Name Age Department Marks   City
0  Tenzin  20        CSE    85    Leh
2   Priya  20        CSE    92    Leh
3    Arun  22         IT    74   None
4  Tenzin  20        CSE    85    Leh
5    None  21         IT    88  Delhi

**fillna()**

Instead of deleting missing values, we can fill them.

In [19]:
# Let's clean the column immediately so it becomes true numbers
# 'errors="coerce"' turns any unreadable text/strings into NaN safely
df["Marks"] = pd.to_numeric(df["Marks"], errors="coerce")

# 1. Fill missing numerical values with a static 0
df["Marks_with_0"] = df["Marks"].fillna(0)

# 2. Fill text missing values with "Unknown"
df["City_with_Unknown"] = df["City"].fillna("Unknown")

# 3. Fill numerical data with the Mean (Average) -> This will NOT crash anymore
df["Marks_with_Mean"] = df["Marks"].fillna(df["Marks"].mean())

# 4. Fill numerical data with the Median (Best for handling outliers)
df["Marks_with_Median"] = df["Marks"].fillna(df["Marks"].median())

# 5. Fill text missing values with the Mode (Most frequent item)
# Fixed: added .iloc[0] to extract the raw text value from the mode series safely
df["City_with_Mode"] = df["City"].fillna(df["City"].mode().iloc[0] if not df["City"].mode().empty else "Unknown")

# Show the cleaned data
print(df.head())

     Name Age Department  Marks     City  Marks_with_0 City_with_Unknown  \
0  Tenzin  20        CSE     85      Leh            85               Leh
1   Rahul  21        cse      0    Delhi             0             Delhi
2   Priya  20        CSE     92      Leh            92               Leh
3    Arun  22         IT     74  Unknown            74           Unknown
4  Tenzin  20        CSE     85      Leh            85               Leh

   Marks_with_Mean  Marks_with_Median City_with_Mode
0               85                 85            Leh
1                0                  0          Delhi
2               92                 92            Leh
3               74                 74        Unknown
4               85                 85            Leh

**duplicated()**

duplicated() identifies duplicate rows.

In [22]:
print(df.duplicated())

#Count duplicates
print(df.duplicated().sum())

0    False
1    False
2    False
3    False
4     True
5    False
dtype: bool
1

**drop_duplicates()**

drop_duplicates() removes duplicate rows.

In [27]:
df = df.drop_duplicates()
print(df)


#Checking Duplicates in a Specific Column
df["Name"].duplicated()
df["Name"].duplicated().sum()
df.drop_duplicates(subset=["Name"])

     Name Age Department  Marks     City  Marks_with_0 City_with_Unknown  \
0  Tenzin  20        CSE     85      Leh            85               Leh
1   Rahul  21        cse      0    Delhi             0             Delhi
2   Priya  20        CSE     92      Leh            92               Leh
3    Arun  22         IT     74  Unknown            74           Unknown
5    None  21         IT     88    Delhi            88             Delhi

   Marks_with_Mean  Marks_with_Median City_with_Mode
0               85                 85            Leh
1                0                  0          Delhi
2               92                 92            Leh
3               74                 74        Unknown
5               88                 88          Delhi

,Name,Age,Department,Marks,City,Marks_with_0,City_with_Unknown,Marks_with_Mean,Marks_with_Median,City_with_Mode
0,Tenzin,20,CSE,85,Leh,85,Leh,85,85,Leh
1,Rahul,21,cse,0,Delhi,0,Delhi,0,0,Delhi
2,Priya,20,CSE,92,Leh,92,Leh,92,92,Leh
3,Arun,22,IT,74,Unknown,74,Unknown,74,74,Unknown
5,None,21,IT,88,Delhi,88,Delhi,88,88,Delhi

**astype()**

astype() is used to change a column's data type.

In [33]:
print(df["Age"].dtype)

#even though Age should be numeric.
df["Age"] = df["Age"].astype(int)
print(df["Age"].dtype)

#Convert Marks
df["Marks"] = df["Marks"].astype(int)
print(df["Marks"].dtype)

#convert to float
df["Marks"] = df["Marks"].astype(float)
print(df["Marks"].dtype)

#convert to string
df["Name"] = df["Name"].astype(str)
print(df["Name"].dtype)

int64
int64
int64
float64
object

**Numerical Columns Stored as Strings**

In [35]:
#  if marks are in string format
df["Marks"] = pd.to_numeric(df["Marks"])

**Handling invalid numerical values**

In [ ]:
df["Marks"] = pd.to_numeric(df["Marks"],errors="coerce")
#The invalid value becomes NaN.

**rename()**

rename() changes column names or index labels.

In [39]:
df = df.rename(columns={
    "Name": "Student_Name",
    "Department": "Dept",
    "Marks": "Score"
})

#Rename one column
df = df.rename(columns={
    "Department": "Dept"
})

**replace()**

replace() replaces specific values.

In [44]:
df["Department"] = df["Department"].replace({
    "cse": "CSE",
    "Cse": "CSE"
})


#Replace multiple values
df["Department"] = df["Department"].replace({
    "cse": "CSE",
    "Cse": "CSE",
    "IT ": "IT"
})


#remove extra spaces:
df["Department"] = df["Department"].str.strip()
df["Department"] = (
    df["Department"]
    .str.strip()
    .str.upper()
)

**Empty Strings vs Missing Values**

In [45]:
'''
Name
----
Tenzin
Rahul
""
Priya
'''
df = df.replace("", pd.NA)